import tkinter
import calendar
screen = tkinter.Tk()
screen.geometry("200x400")
screen.title("Calendar")
label = tkinter.Label(screen,text = "Calendar",bg = "grey",fg = "black")
label1 = tkinter.Label(screen,text = "Enter year",bg = "green",fg = "black")
entry = tkinter.Entry(screen)
def function():
    year = int(entry.get())
    screen1 = tkinter.Tk()
    screen1.geometry("600x500")
    screen1.title("Calander"+str(year))
    text = tkinter.Text(screen1)
    text.pack()
    calendartext = calendar.calendar(year)
    text.insert(tkinter.END,calendartext)
    screen1.mainloop()
button = tkinter.Button(screen,text = "Show Calendar",bg = "red",fg = "black",command = function)
button1 = tkinter.Button(screen,text = "Exit",bg = "red",fg = "black")
label.pack()
label1.pack()
entry.pack()
button.pack()
button1.pack()
screen.mainloop()